name: Generate PDF

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: html to pdf
      uses: LukaszLapaj/html-to-pdf-action@master
      with:
        htmlFile: ./public/index.html
        outputFile: ./pdf/resume.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

