name: Generate PDF

on:
  push:
    tags:        
      - '**' 
  page_build:

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set polish language
      run: echo "LANGUAGE=pl" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/pl')

    - name: html to pdf
      uses: LukaszLapaj/html-to-pdf-action@master
      with:
        htmlFile: ./index.html?lang=${{ env.LANGUAGE }}
        outputFile: ./Michał_Lechowicz_Resume.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "1mm"}}'

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Resume
        path: ./Michał_Lechowicz_Resume.pdf

    - name: Delete old Resume
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: main
        assets: '*.*'
        fail-if-no-assets: false
        fail-if-no-release: false
      if: github.ref == 'refs/heads/master'

    - name: Release to main
      uses: softprops/action-gh-release@v1
      with:
        files: Michał_Lechowicz_Resume.pdf
        tag_name: main
      if: github.ref == 'refs/heads/master'
      
    - name: Release to tag
      uses: softprops/action-gh-release@v1
      with:
        files: Michał_Lechowicz_Resume.pdf
      if: startsWith(github.ref, 'refs/tags/')
