name: Generate PDF

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: HTML to PDF
      uses: fifsky/html-to-pdf-action@v0.1.0
      with:
        htmlFile: ./index.html
      #   outputFile: ./pdf/CV.pdf
      #   pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

